### PR TITLE
feat: add a dds-portfolio client

### PR DESCRIPTION
**Pull request by nvunnamm**
feat:  added missing space in redirect url dds-portfolio client

### CODE REVIEW

**Review by arcshiftsolutions — APPROVED** [review]

**Comment by arcshiftsolutions** [comment]
@nvunnamm - Looks like we'll need to add a space in between the redirectURIs (validation failed)

**Review by arcshiftsolutions — APPROVED** [review]

**Comment by arcshiftsolutions** [comment]
@nvunnamm - It didn't like our commit comment either :)

**Comment by arcshiftsolutions** [comment]
Looks like we'll need something like: 

feat(blog): added client for XYZ

**Comment by junminahn** [comment]
@nvunnamm  I see 1 change here, did we update the client `work-bc-teacher-resources` manually before?

**Comment by nvunnamm** [comment]
yeah Junmin we had updated work-bc-teacher-resources client redirect url manually in our keyclock instance

**Comment by junminahn** [comment]
@nvunnamm I see. let's avoid creating and updating things manually to avoid any conflicts and actually when merging this or, the changes will be reversed as defined in this repository. So, let's update the `work-bc-teacher-resources` client file.
Note that Terraform is a tool that takes a declarative approach over an imperative way, meaning that the infrastructure and configurations are updated accordingly.

**Comment by nvunnamm** [comment]
sure @junminahn, currently this merge is blocked by "The base branch requires all commits to be signed". Can I go ahead and disable those settings to have signed commits?

**Comment by junminahn** [comment]
@nvunnamm it is all about `Team Agreements` which determined by me and @ConradBoydElliottGustafson in an early time.
`GPG Signing commits` are recommended by GitHub.
```
Using GPG or S/MIME, you can sign tags and commits locally. These tags or commits are marked as verified on GitHub so other people can be confident that the changes come from a trusted source.
```
https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification

But, if the team does not want to have this as the `team agreements` and `convention`, we definitely need to disable this.
I would like to hear about other teams' opinions before deciding things between us.
@arcshiftsolutions  @ConradBoydElliottGustafson @brycereid73

**Comment by arcshiftsolutions** [comment]
@junminahn @nvunnamm - Very interesting question; there's a lot of different perspectives on this. Most teams would tell you it's not required while some would say you absolutely need it. Good detail here:

https://softwareengineering.stackexchange.com/questions/212192/what-are-the-advantages-and-disadvantages-of-cryptographically-signing-commits-a

https://mikegerwitz.com/2012/05/a-git-horror-story-repository-integrity-with-signed-commits

I'm happy to go either way in this case.

**Comment by ConradBoydElliottGustafson** [comment]
I vote that we keep the practices suggested by @junminahn over at https://github.com/bcgov/sso_terraform/blob/master/docs/developer-guide.md

Let's be really disciplined in our practices so that nobody can ever call us sloppy!

**Comment by junminahn** [comment]
@nvunnamm if interested, there is a little doc describing `GPG key signed commits` and `pre-commit hooks` in this repo.
https://github.com/bcgov/sso_terraform/blob/master/docs/developer-guide.md

note that `asdf` is not required to install `pre-commit` and `gitlint` as long as you have `python` installed locally.
and please feel free to reach out if having any issues around this.

I think we can split the task into the little bit smaller chunks as:
1. setup `GPG key` to sign commits.
2. setup `pre-commit hooks` locally.
3. create a PR in another branch to update `redirect_url` for `work-bc-teacher-resources` first.
4. re-create a PR in another branch  `dds-portfolio` as it will be more challenge to signs commits already pushed.

**Comment by junminahn** [comment]
closed on behalf of #16  and #17

**Pull request closed without merging**
